import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import GeneralStateProvider from "@/context/GeneralStateProvider";
import localFont from "next/font/local";

const myFont = localFont({
  src: "../../fonts/TBCXMedium.ttf",
  fallback: ["sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};
export default function LocaleLayout({
  children,
  params: {locale}
}: {
  children: React.ReactNode;
  params: {locale: string};
})  {
  return (
    <html lang={locale} suppressHydrationWarning>
     <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
     </head>
      
      <body className={myFont.className}>
        <GeneralStateProvider>
          {children}
          <Toaster />
        </GeneralStateProvider>
      </body>
    </html>
  );
}
